### ISSUE TITLE
Failing to create model for LAMMPS usage

### ISSUE THREAD

**Issue by frostedoyster** [MDIL-SNU/SevenNet#150]
First of all, thanks for all the work that went into the models and the library! I find this to be one of the best models out there.
With the latest version (installed with `pip install sevenn`), I get this error when trying to export a model for LAMMPS inference:
```
$ sevenn_get_model 7net-0
Traceback (most recent call last):
  File ".../bin/sevenn_get_model", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File ".../site-packages/sevenn/main/sevenn_get_model.py", line 59, in main
    run(args)
  File ".../site-packages/sevenn/main/sevenn_get_model.py", line 42, in run
    deploy(stct_dct, config, output_prefix)
  File ".../site-packages/sevenn/scripts/deploy.py", line 27, in deploy
    model.prepand_module('edge_preprocess', EdgePreprocess(True))
  File ".../site-packages/sevenn/nn/sequential.py", line 83, in prepand_module
    self._modules.move_to_end(key, last=False)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'move_to_end'
```
Let me know how if I can help fix the issue

**Comment by YutackPark** [comment]
Thanks for reaching out. Have you checked torch version? We have a bug in
latest torch versions (>=2.5.0), when using LAMMPS (therefore torchscript)

2024년 12월 21일 (토) 오후 4:01, Filippo Bigi ***@***.***>님이 작성:

**Comment by frostedoyster** [comment]
Thank you! Indeed it works now with `torch<2.5.0`

**Comment by thangckt** [comment]
hi @YutackPark 
seemly that many people get this 
can you consider put `'torch<2.5.0'` in `.toml` file?

**Comment by YutackPark** [comment]
#164
